llms:
  openai_default:
    model_name: gpt-5
    base_url: https://api.ikuncode.cc/v1
    api_key_env: OPENAI_API_KEY
    temperature: 0.6

  deepseek_default:
    model_name: deepseek-chat
    base_url: https://api.deepseek.com/v1
    api_key_env: DEEPSEEK_API_KEY
    temperature: 0.0

  qwen_default:
    model_name: qwen-plus
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
    api_key_env: QWEN_API_KEY
    temperature: 0.0

  ollama_default:
    model_name: qwen2.5:7b-instruct
    base_url: http://127.0.0.1:11434/v1
    api_key_env: OLLAMA_API_KEY
    temperature: 0.0
